# 1. 빌드 환경 설정
FROM openjdk:21-jdk-slim-buster AS builder

# 도커를 관리하기 위한 도구 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# gradle 설정 파일 복사
COPY gradlew build.gradle settings.gradle ./
COPY gradle ./gradle

# gradlew 실행 권한 추가
RUN chmod +x gradlew

# gradle 빌드 실행
RUN ./gradlew clean build -x test

# 2. 실행 환경 설정
FROM openjdk:21-jdk-slim-buster

WORKDIR /app

# 빌드된 JAR 파일만 복사
COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

# JAR 파일 실행
CMD ["java", "-jar", "app.jar"]
